/**
 * Macro Analysis Series Catalogs
 * Organized by geography and asset class
 */

export interface MacroSeriesInfo {
  id: string;
  name: string;
  description: string;
  units: string;
  source: string;
  calculation?: string;
  updateFrequency: string;
  notes?: string;
}

// U.S. Macro
export const US_MACRO: MacroSeriesInfo[] = [
  {
    id: "GDP",
    name: "GDP",
    description: "Gross Domestic Product",
    units: "Billions",
    source: "U.S. Bureau of Economic Analysis (BEA)",
    calculation: "Total market value of all final goods and services produced in the U.S.",
    updateFrequency: "Quarterly",
    notes: "Primary measure of economic output. Healthy growth is 2-3% annually.",
  },
  {
    id: "GDPC1",
    name: "Real GDP",
    description: "Real Gross Domestic Product",
    units: "Billions (2017 $)",
    source: "U.S. Bureau of Economic Analysis (BEA)",
    calculation: "GDP adjusted for inflation using 2017 as base year",
    updateFrequency: "Quarterly",
    notes: "Inflation-adjusted GDP for meaningful time comparisons.",
  },
  {
    id: "UNRATE",
    name: "Unemployment Rate",
    description: "Civilian unemployment rate",
    units: "%",
    source: "U.S. Bureau of Labor Statistics (BLS)",
    calculation: "Unemployed persons divided by civilian labor force",
    updateFrequency: "Monthly",
    notes: "Rates above 5% typically signal economic weakness.",
  },
  {
    id: "PAYEMS",
    name: "Nonfarm Payroll",
    description: "Total nonfarm payroll employment",
    units: "Thousands",
    source: "U.S. Bureau of Labor Statistics (BLS)",
    calculation: "Total paid employees excluding farm workers and some other categories",
    updateFrequency: "Monthly",
    notes: "200k+ monthly job gains considered strong growth.",
  },
  {
    id: "CPIAUCSL",
    name: "CPI",
    description: "Consumer Price Index",
    units: "Index",
    source: "U.S. Bureau of Labor Statistics (BLS)",
    calculation: "Average price change for urban consumer market basket, 1982-84=100",
    updateFrequency: "Monthly",
    notes: "Primary inflation gauge. Fed targets 2% annual inflation.",
  },
  {
    id: "FEDFUNDS",
    name: "Fed Funds Rate",
    description: "Effective federal funds rate",
    units: "%",
    source: "Federal Reserve Board",
    calculation: "Volume-weighted median rate on overnight federal funds transactions",
    updateFrequency: "Daily",
    notes: "Fed's primary monetary policy tool. Influences all other rates.",
  },
  {
    id: "DGS10",
    name: "10-Year Treasury",
    description: "10-year constant maturity rate",
    units: "%",
    source: "U.S. Department of Treasury",
    calculation: "Market yield interpolated from daily yield curve",
    updateFrequency: "Daily",
    notes: "Benchmark for mortgage rates and long-term borrowing costs.",
  },
  {
    id: "DGS2",
    name: "2-Year Treasury",
    description: "2-year constant maturity rate",
    units: "%",
    source: "U.S. Department of Treasury",
    calculation: "Market yield interpolated from daily yield curve",
    updateFrequency: "Daily",
    notes: "Reflects Fed policy expectations over next 2 years.",
  },
  {
    id: "T10Y2Y",
    name: "Yield Curve Spread",
    description: "10Y-2Y Treasury spread",
    units: "%",
    source: "Federal Reserve Board (calculated)",
    calculation: "10-Year Treasury yield minus 2-Year Treasury yield",
    updateFrequency: "Daily",
    notes: "Inversions have preceded every recession since 1955.",
  },
  {
    id: "SP500",
    name: "S&P 500",
    description: "S&P 500 stock index",
    units: "Index",
    source: "S&P Dow Jones Indices",
    calculation: "Market-cap weighted index of 500 leading U.S. companies",
    updateFrequency: "Daily (trading days)",
    notes: "Represents ~80% of U.S. stock market capitalization.",
  },
  {
    id: "VIXCLS",
    name: "VIX",
    description: "CBOE Volatility Index",
    units: "Index",
    source: "Chicago Board Options Exchange (CBOE)",
    calculation: "Implied volatility from S&P 500 options, 30-day expected volatility",
    updateFrequency: "Daily (trading days)",
    notes: "Fear gauge. VIX > 30 = high fear. VIX < 15 = complacency.",
  },
  {
    id: "M2SL",
    name: "M2 Money Supply",
    description: "M2 money stock",
    units: "Billions",
    source: "Federal Reserve Board",
    calculation: "M1 plus savings deposits, money market funds, and small time deposits",
    updateFrequency: "Weekly",
    notes: "Rapid growth can signal inflation risk.",
  },
  {
    id: "DEXUSEU",
    name: "USD/EUR",
    description: "US Dollar to Euro exchange rate",
    units: "USD per EUR",
    source: "Federal Reserve Board (H.10 release)",
    calculation: "Noon buying rate in New York for cable transfers",
    updateFrequency: "Daily",
    notes: "Most traded currency pair globally.",
  },
  {
    id: "RSXFS",
    name: "Retail Sales",
    description: "Advance retail sales",
    units: "Millions",
    source: "U.S. Census Bureau",
    calculation: "Total sales at retail and food service stores",
    updateFrequency: "Monthly",
    notes: "Consumer spending is 70% of U.S. GDP.",
  },
  {
    id: "HOUST",
    name: "Housing Starts",
    description: "New privately owned housing starts",
    units: "Thousands",
    source: "U.S. Census Bureau",
    calculation: "Number of new residential construction projects started",
    updateFrequency: "Monthly",
    notes: "Normal level is 1.4-1.6M annually.",
  },
  {
    id: "UMCSENT",
    name: "Consumer Sentiment",
    description: "University of Michigan sentiment",
    units: "Index",
    source: "University of Michigan",
    calculation: "Survey-based confidence index, 1966 Q1=100",
    updateFrequency: "Monthly",
    notes: "Above 90 = optimism. Below 70 = pessimism.",
  },
];

// Global Macro
export const GLOBAL_MACRO: MacroSeriesInfo[] = [
  {
    id: "NYGDPMKTPCDWLD",
    name: "World GDP",
    description: "World GDP at market prices",
    units: "Billions",
    source: "World Bank",
    calculation: "Sum of all countries' GDP at market prices",
    updateFrequency: "Annually",
    notes: "Global economic output. ~$100 trillion in 2023.",
  },
  {
    id: "DEXUSEU",
    name: "USD/EUR",
    description: "US Dollar to Euro",
    units: "USD per EUR",
    source: "Federal Reserve Board",
    calculation: "Noon buying rate in New York",
    updateFrequency: "Daily",
    notes: "Higher = stronger euro / weaker dollar.",
  },
  {
    id: "DEXJPUS",
    name: "JPY/USD",
    description: "Japanese Yen to US Dollar",
    units: "JPY per USD",
    source: "Federal Reserve Board",
    calculation: "Noon buying rate in New York",
    updateFrequency: "Daily",
    notes: "Safe-haven currency. Strengthens during risk-off events.",
  },
  {
    id: "DEXCHUS",
    name: "CNY/USD",
    description: "Chinese Yuan to US Dollar",
    units: "CNY per USD",
    source: "Federal Reserve Board",
    calculation: "Noon buying rate in New York",
    updateFrequency: "Daily",
    notes: "Managed by People's Bank of China within a band.",
  },
  {
    id: "DEXINUS",
    name: "INR/USD",
    description: "Indian Rupee to US Dollar",
    units: "INR per USD",
    source: "Federal Reserve Board",
    calculation: "Noon buying rate in New York",
    updateFrequency: "Daily",
    notes: "Emerging market currency. Reflects India's growth.",
  },
  {
    id: "DEXUSUK",
    name: "USD/GBP",
    description: "US Dollar to British Pound",
    units: "USD per GBP",
    source: "Federal Reserve Board",
    calculation: "Noon buying rate in New York",
    updateFrequency: "Daily",
    notes: "Affected by Brexit and Bank of England policy.",
  },
  {
    id: "DCOILWTICO",
    name: "WTI Crude Oil",
    description: "West Texas Intermediate crude oil prices",
    units: "$/Barrel",
    source: "U.S. Energy Information Administration",
    calculation: "Spot price for WTI crude at Cushing, Oklahoma",
    updateFrequency: "Daily",
    notes: "U.S. oil benchmark. Inflation and growth indicator.",
  },
  {
    id: "GOLDAMGBD228NLBM",
    name: "Gold Price",
    description: "Gold fixing price",
    units: "$/Oz",
    source: "ICE Benchmark Administration",
    calculation: "3:00 PM London fix",
    updateFrequency: "Daily",
    notes: "Safe-haven asset. Inverse to real interest rates.",
  },
  {
    id: "DEXBZUS",
    name: "BRL/USD",
    description: "Brazilian Real to US Dollar",
    units: "BRL per USD",
    source: "Federal Reserve Board",
    calculation: "Noon buying rate in New York",
    updateFrequency: "Daily",
    notes: "Largest economy in South America.",
  },
  {
    id: "DEXMXUS",
    name: "MXN/USD",
    description: "Mexican Peso to US Dollar",
    units: "MXN per USD",
    source: "Federal Reserve Board",
    calculation: "Noon buying rate in New York",
    updateFrequency: "Daily",
    notes: "Closely tied to U.S. economy via trade.",
  },
  {
    id: "DTWEXBGS",
    name: "Trade Weighted USD Index",
    description: "Broad dollar index",
    units: "Index",
    source: "Federal Reserve Board",
    calculation: "Weighted average of USD vs major currencies, Jan 2006=100",
    updateFrequency: "Daily",
    notes: "Comprehensive measure of dollar strength.",
  },
  {
    id: "INTDSRUSM193N",
    name: "US Interest Rates",
    description: "Interest rates, discount rate for US",
    units: "%",
    source: "International Monetary Fund",
    calculation: "Federal Reserve discount rate",
    updateFrequency: "Monthly",
    notes: "Rate at which Fed lends to banks.",
  },
];

// China Macro
export const CHINA_MACRO: MacroSeriesInfo[] = [
  {
    id: "MKTGDPCNA646NWDB",
    name: "China GDP",
    description: "GDP at market prices",
    units: "Billions",
    source: "World Bank",
    calculation: "Total market value of China's economic output",
    updateFrequency: "Annually",
    notes: "Second largest economy. ~$18 trillion in 2023.",
  },
  {
    id: "DEXCHUS",
    name: "CNY/USD",
    description: "Chinese Yuan to US Dollar exchange rate",
    units: "CNY per USD",
    source: "Federal Reserve Board",
    calculation: "Noon buying rate in New York",
    updateFrequency: "Daily",
    notes: "PBOC manages within trading band. ~7 CNY/USD typical.",
  },
  {
    id: "CPALTT01CNM657N",
    name: "China CPI",
    description: "Consumer Price Index for China",
    units: "Index",
    source: "OECD",
    calculation: "Consumer price index for China",
    updateFrequency: "Monthly",
    notes: "Inflation in China. Government targets ~3%.",
  },
  {
    id: "CHNCPIALLMINMEI",
    name: "China Inflation Rate",
    description: "CPI annual inflation",
    units: "%",
    source: "OECD",
    calculation: "Year-over-year change in CPI",
    updateFrequency: "Monthly",
    notes: "China's inflation rate, typically lower than West.",
  },
  {
    id: "LRUN64TTCNQ156S",
    name: "China Unemployment",
    description: "Harmonized unemployment rate",
    units: "%",
    source: "OECD",
    calculation: "Standardized unemployment rate",
    updateFrequency: "Quarterly",
    notes: "Official rate ~5%. Actual may be higher.",
  },
  {
    id: "CHNPOPULATION",
    name: "China Population",
    description: "Total population",
    units: "Persons",
    source: "World Bank",
    calculation: "Total population count",
    updateFrequency: "Annually",
    notes: "~1.4 billion. Declining due to aging and low birth rate.",
  },
  {
    id: "XTEXVA01CNM667S",
    name: "China Exports",
    description: "Exports of goods and services",
    units: "%",
    source: "OECD",
    calculation: "Percentage of GDP from exports",
    updateFrequency: "Monthly",
    notes: "Major exporter. Trade tensions with U.S. impactful.",
  },
  {
    id: "XTIMVA01CNM667S",
    name: "China Imports",
    description: "Imports of goods and services",
    units: "%",
    source: "OECD",
    calculation: "Percentage of GDP from imports",
    updateFrequency: "Monthly",
    notes: "Strong imports signal domestic demand growth.",
  },
];

// India Macro
export const INDIA_MACRO: MacroSeriesInfo[] = [
  {
    id: "MKTGDPINA646NWDB",
    name: "India GDP",
    description: "GDP at market prices",
    units: "Billions",
    source: "World Bank",
    calculation: "Total market value of India's economic output",
    updateFrequency: "Annually",
    notes: "Fastest growing major economy. ~$3.7 trillion in 2023.",
  },
  {
    id: "DEXINUS",
    name: "INR/USD",
    description: "Indian Rupee to US Dollar exchange rate",
    units: "INR per USD",
    source: "Federal Reserve Board",
    calculation: "Noon buying rate in New York",
    updateFrequency: "Daily",
    notes: "Gradual depreciation trend. ~83 INR/USD in 2024.",
  },
  {
    id: "CPALTT01INM657N",
    name: "India CPI",
    description: "Consumer Price Index for India",
    units: "Index",
    source: "OECD",
    calculation: "Consumer price index for India",
    updateFrequency: "Monthly",
    notes: "Inflation target is 4% +/- 2%.",
  },
  {
    id: "INDCPIALLMINMEI",
    name: "India Inflation Rate",
    description: "CPI annual inflation",
    units: "%",
    source: "OECD",
    calculation: "Year-over-year CPI change",
    updateFrequency: "Monthly",
    notes: "Higher than developed markets. Food inflation volatile.",
  },
  {
    id: "LRUN64TTINQ156S",
    name: "India Unemployment",
    description: "Harmonized unemployment rate",
    units: "%",
    source: "OECD",
    calculation: "Standardized unemployment rate",
    updateFrequency: "Quarterly",
    notes: "Youth unemployment a concern. Job creation priority.",
  },
  {
    id: "INDPOPULATION",
    name: "India Population",
    description: "Total population",
    units: "Persons",
    source: "World Bank",
    calculation: "Total population count",
    updateFrequency: "Annually",
    notes: "Surpassed China as most populous. ~1.4 billion. Demographic dividend.",
  },
  {
    id: "XTEXVA01INM667S",
    name: "India Exports",
    description: "Exports of goods and services",
    units: "%",
    source: "OECD",
    calculation: "Percentage of GDP from exports",
    updateFrequency: "Monthly",
    notes: "Services exports (IT, BPO) significant.",
  },
  {
    id: "XTIMVA01INM667S",
    name: "India Imports",
    description: "Imports of goods and services",
    units: "%",
    source: "OECD",
    calculation: "Percentage of GDP from imports",
    updateFrequency: "Monthly",
    notes: "Energy imports major portion. Oil price sensitive.",
  },
  {
    id: "INDNGDP",
    name: "India Nominal GDP",
    description: "Nominal GDP",
    units: "Billions",
    source: "International Monetary Fund",
    calculation: "GDP at current prices (not inflation-adjusted)",
    updateFrequency: "Annually",
    notes: "Growing 6-8% annually. On track to be 3rd largest economy.",
  },
];

// Europe Macro
export const EUROPE_MACRO: MacroSeriesInfo[] = [
  {
    id: "CLVMNACSCAB1GQEU272020",
    name: "Eurozone GDP",
    description: "Real GDP for Euro Area",
    units: "Billions",
    source: "Eurostat",
    calculation: "Chain-linked GDP for 20 Euro Area countries",
    updateFrequency: "Quarterly",
    notes: "Combined GDP of eurozone nations. ~$14 trillion.",
  },
  {
    id: "DEXUSEU",
    name: "USD/EUR",
    description: "US Dollar to Euro exchange rate",
    units: "USD per EUR",
    source: "Federal Reserve Board",
    calculation: "Noon buying rate in New York",
    updateFrequency: "Daily",
    notes: "Parity (~1.0) signals equal strength. Above = strong euro.",
  },
  {
    id: "CP0000EZ19M086NEST",
    name: "Eurozone CPI",
    description: "Harmonized CPI",
    units: "Index",
    source: "Eurostat",
    calculation: "Harmonized index of consumer prices for eurozone",
    updateFrequency: "Monthly",
    notes: "ECB targets 2% inflation over medium term.",
  },
  {
    id: "LRHUTTTTEZM156S",
    name: "Eurozone Unemployment",
    description: "Harmonized unemployment rate",
    units: "%",
    source: "Eurostat",
    calculation: "Standardized unemployment for euro area",
    updateFrequency: "Monthly",
    notes: "Varies widely by country. Spain/Italy higher than Germany.",
  },
  {
    id: "ECBDFR",
    name: "ECB Deposit Rate",
    description: "European Central Bank deposit facility rate",
    units: "%",
    source: "European Central Bank",
    calculation: "Rate on ECB deposit facility",
    updateFrequency: "Policy meetings (~6-8 per year)",
    notes: "ECB's policy rate. Influences all eurozone rates.",
  },
  {
    id: "DEXUSUK",
    name: "USD/GBP",
    description: "US Dollar to British Pound",
    units: "USD per GBP",
    source: "Federal Reserve Board",
    calculation: "Noon buying rate in New York",
    updateFrequency: "Daily",
    notes: "Brexit impact significant. Pound volatility elevated post-2016.",
  },
  {
    id: "GBRUNEPR",
    name: "UK Unemployment",
    description: "UK unemployment rate",
    units: "%",
    source: "Office for National Statistics (UK)",
    calculation: "Percentage of labor force unemployed",
    updateFrequency: "Monthly",
    notes: "Post-Brexit labor market tight. Immigration changes affect.",
  },
  {
    id: "GBRCPIALLMINMEI",
    name: "UK Inflation",
    description: "UK CPI inflation rate",
    units: "%",
    source: "OECD",
    calculation: "Year-over-year CPI change for UK",
    updateFrequency: "Monthly",
    notes: "Bank of England targets 2%. Spiked post-COVID.",
  },
  {
    id: "CLVMNACSCAB1GQUK",
    name: "UK GDP",
    description: "Real GDP for United Kingdom",
    units: "Billions",
    source: "Office for National Statistics (UK)",
    calculation: "Chained-volume GDP",
    updateFrequency: "Quarterly",
    notes: "~$3.1 trillion economy. 6th largest globally.",
  },
  {
    id: "DEUCPIALLMINMEI",
    name: "Germany Inflation",
    description: "Germany CPI inflation",
    units: "%",
    source: "OECD",
    calculation: "Year-over-year CPI change for Germany",
    updateFrequency: "Monthly",
    notes: "Largest eurozone economy. Inflation averse culture.",
  },
  {
    id: "LRUN64TTDEM156S",
    name: "Germany Unemployment",
    description: "Germany unemployment rate",
    units: "%",
    source: "OECD",
    calculation: "Standardized unemployment for Germany",
    updateFrequency: "Monthly",
    notes: "Typically lowest in eurozone. Strong manufacturing base.",
  },
];

// Bitcoin & Crypto
export const BITCOIN_MACRO: MacroSeriesInfo[] = [
  {
    id: "CBBTCUSD",
    name: "Bitcoin Price",
    description: "Coinbase Bitcoin price in USD",
    units: "USD",
    source: "Coinbase (via FRED)",
    calculation: "Daily closing price of Bitcoin on Coinbase exchange",
    updateFrequency: "Daily",
    notes: "Digital gold narrative. 21M supply cap. Halving every 4 years. Volatile but institutional adoption growing.",
  },
];

export function getSeriesByRegion(region: string): MacroSeriesInfo[] {
  switch (region) {
    case "us":
      return US_MACRO;
    case "global":
      return GLOBAL_MACRO;
    case "china":
      return CHINA_MACRO;
    case "india":
      return INDIA_MACRO;
    case "europe":
      return EUROPE_MACRO;
    case "bitcoin":
      return BITCOIN_MACRO;
    default:
      return [];
  }
}

export function getMacroSeriesById(id: string): MacroSeriesInfo | undefined {
  const allSeries = [
    ...US_MACRO,
    ...GLOBAL_MACRO,
    ...CHINA_MACRO,
    ...INDIA_MACRO,
    ...EUROPE_MACRO,
    ...BITCOIN_MACRO,
  ];
  return allSeries.find((s) => s.id === id);
}
